### PR TITLE
Solved Issue #21 : Initial date set to receive mails from by user

### PR DESCRIPTION
**Pull request by accakks**
On syncing, mails were being retrived from set date

### CODE REVIEW

**Comment by inishchith** [comment]
@accakks we need that field . please refer the email account form of ERPNext

**Comment by accakks** [comment]
Why do we need it? 
We are already setting sync limits and everything?

And if we do, shouldn't it be asked from user? Instead of setting up in the program?

**Comment by inishchith** [comment]
> And if we do, shouldn't it be asked from user? Instead of setting up in the program?

YES , but thats just a minor thing to work on . there are major issue that we're supposed to be working on right now .
@accakks

**Comment by accakks** [comment]
#21

**Comment by accakks** [comment]
@inishchith Updated!

**Pull request merged**
