### PR TITLE
Solved : Read only method for emails [improvements]

### PR DESCRIPTION
**Pull request by accakks**
#16 
Result : Received mails cannot be edited

### CODE REVIEW

**Comment by inishchith** [comment]
@accakks I'll test this locally in some time and merge .

**Comment by accakks** [comment]
Hi @inishchith  need to make some changes. Do not merge for now

**Comment by inishchith** [comment]
@accakks any updates ?

**Comment by accakks** [comment]
Approach I was using creates some other complications. I'm looking for a. simpler way. I'll maybe discuss this tomm with suraj.

**Comment by accakks** [comment]
#27

**Pull request closed without merging**
